cs_catalog_slug: "products"
p_catalog_slug: "products"
cs_listing_slug: "tovary"
p_listing_slug: "predl"


activities: ['phone_hits']

project: "blizko"
stand_link: "test-blizko.ru"
company_slug: "test"

host: "localhost"
port: "5432"
db: "blizko_stat"
username: "postgres"
password: "12345"
