cs_catalog_slug: "products"
p_catalog_slug: "products"
p_listing_slug: "price"

activities: ['phone_hits']

project: "blizko"
stand_link: "www.test-blizko.ru"
company_url: "test.test-blizko.ru"

host: "localhost"
port: "5432"
db: "blizko_stat"
username: "postgres"
password: "12345"
